### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by seongilp** [typesense/typesense-instantsearch-demo#8]
## Description

Hi, I am trying to follow the demo but it doesn't work.
Search engine would be okay but demo page doesn't

## Steps to reproduce

![](https://images.velog.io/images/oamullu/post/c4edbc9f-f24f-417f-b913-b2c0a4e862f8/Screenshot%20from%202021-05-31%2020-50-09.png)

## Expected Behavior

something has been shown on the screen

## Actual Behavior

![](https://images.velog.io/images/oamullu/post/c4edbc9f-f24f-417f-b913-b2c0a4e862f8/Screenshot%20from%202021-05-31%2020-50-09.png)

## Metadata

**Typsense Version**: 0.20

**OS**: Linux,

**Comment by seongilp** [comment]
Solved

**Comment by prmichaelsen** [comment]
Thanks for posting your solution
